name: Hello World From Python
on:
  schedule:
    - cron:  '* 1 * * *'
  workflow_dispatch:
jobs:
  hello_world_job:
    name: A greeting job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run the script
      run: python main.py
